fail safely if IMDSv2 token not found
fixing @tolitius suggestion.
fail safely if the metadata token cannot be retrieved, as this is essential for this module to function correctly.

diff --git a/modules/run-nomad/run-nomad b/modules/run-nomad/run-nomad
--- a/modules/run-nomad/run-nomad
+++ b/modules/run-nomad/run-nomad
@@ -277,6 +277,11 @@ function generate_nomad_config {
 
   metadata_token=$(get_metadata_token)
 
+  if [[ -z "$metadata_token" ]]; then
+    log_error "could not retrieve IMDSv2 token. exiting. check if your launch template metadata options have http_tokens set to required and http_endpoint set to enabled."
+    exit 1
+  fi
+
   instance_id=$(get_instance_id "$metadata_token")
   instance_ip_address=$(get_instance_ip_address "$metadata_token")
   instance_region=$(get_instance_region "$metadata_token")
